### PR TITLE
Implementation of build steps and support for old API

### PR DESCRIPTION
**Pull request by axtimhaus**
#### Changes

- build step system as discussed in #28  was implemented
- latexmk build step with support for old API and deprecation warning was implemented

#### Todo

- [x] Check if tests must be changed and/or extended (current tests passing)
- [ ] update docs

### CODE REVIEW

**Comment by tobiasraabe** [comment]
Hi @axtimhaus, this looks awesome! Can I offer any help or are you just looking for some time to finish the implementation?

**Comment by axtimhaus** [comment]
If you would check up the tests I would be thankful ;)
I'm going to build the other build steps soon.

**Comment by tobiasraabe** [comment]
Hi @axtimhaus,

I got the tests running and made some changes to the code. Here is some feedback:

- I had to remove the generator approach for the build steps since task functions are pickled during parallelization and generators are not pickable.
- During development, try to keep the tests passing. Otherwise, you might later need to fix many bugs at once.
- Moreover, I found it helpful to, first, implement tests for new features and, secondly, the feature. The tests ensure the correctness of the implementation and help you to focus on the necessary changes.

**Comment by axtimhaus** [comment]
Hi @tobiasraabe,

yes, you are right, I lack a bit of discipline in that stuff...
I often work with code that is not testable very well, so I have to get used to it.
But I ran the tests after my changes, and all existing ones were passing. Maybe something went wrong, have to check this.

So could I get over to implement the other steps?

**Comment by tobiasraabe** [comment]
No problem. If you like you can move over implementing the other build steps.

I'll wrap up this PR probably on Monday and document the new interface.

**Comment by tobiasraabe** [comment]
Hi @axtimhaus, I finished the readme. Just one thing which might sound silly. If people want to abbreviate the import for the build steps, they might do ``from pytask_latex import build_steps as bs``. You can call it a namespace collision. Would you be fine with renaming it to `compilation_steps`?

**Pull request merged**
